PREFIX locn:  <http://www.w3.org/ns/locn#>
PREFIX vcard: <http://www.w3.org/2006/vcard/ns#>

CONSTRUCT {
  ?Location a vcard:Location ;
    vcard:fn ?geographicName
} WHERE {
  ?Location locn:geographicName ?geographicName
}
